-- Local stand-ins for platform-owned tables; never a production migration.
BEGIN;
CREATE TABLE IF NOT EXISTS firms (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    balance_cents INTEGER NOT NULL,
    uuid TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payer_firm_id INTEGER NOT NULL,
    payee_firm_id INTEGER NOT NULL,
    amount_cents INTEGER NOT NULL,
    description TEXT NOT NULL
);
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM firms) THEN
        INSERT INTO firms (id, name, balance_cents, uuid) VALUES
            (1, 'Pinecrest CPA Group', 5000000, '3f1c9a2e-7b4d-4c1e-9a55-2d8e6f0b7c41'),
            (2, 'Lopez Bookkeeping', 50000, '8b2e4c71-0d3a-4f6e-b1c9-5a7d2e9f4c10'),
            (3, 'Nair Tax Services', 200000, 'e5f18b3c-2a9d-4c07-8e6b-1d4a7f9c3b25');
        PERFORM setval(pg_get_serial_sequence('firms', 'id'), 3);
    END IF;
END $$;
COMMIT;
