from collections.abc import Callable, Iterator
from contextlib import ExitStack
from dataclasses import asdict
from typing import Any
from uuid import uuid4

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import Connection, Engine, create_engine, text

from firm_payments_service import main
from firm_payments_service.api import health
from firm_payments_service.config import Settings
from firm_payments_service.db import session

from .factories import Firm, FirmFactory, Payload, PaymentFactory, request_for

SeedFirm = Callable[..., Firm]
Snapshot = Callable[[], dict[str, list[tuple[Any, ...]]]]
ClientFactory = Callable[[], TestClient]
Failure = Callable[[str], None]
ENDPOINT = "/api/v1/payments/bulk"


@pytest.fixture(scope="session")
def db_engine() -> Iterator[Engine]:
    admin = create_engine(Settings().database_url, isolation_level="AUTOCOMMIT")
    name = f"payment_tests_{uuid4().hex}"
    engine = create_engine(
        admin.url.set(database=name),
        pool_size=10,
        connect_args={"options": "-csearch_path=public,firm_payments_service"},
    )
    created = False
    try:
        with admin.connect() as connection:
            connection.execute(text(f'CREATE DATABASE "{name}"'))
        created = True
        with engine.begin() as connection:
            connection.execute(
                text("""
                CREATE TABLE firms (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL, balance_cents INTEGER NOT NULL,
                    uuid TEXT NOT NULL
                );
                CREATE TABLE payments (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    payer_firm_id INTEGER NOT NULL,
                    payee_firm_id INTEGER NOT NULL,
                    amount_cents INTEGER NOT NULL, description TEXT NOT NULL
                );
                CREATE SCHEMA firm_payments_service;
                CREATE TABLE firm_payments_service.firm_payments_audit (
                    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    request_id UUID NOT NULL, raw_request JSON NOT NULL
                )
            """)
            )
        yield engine
    finally:
        engine.dispose()
        if created:
            with admin.connect() as connection:
                connection.execute(text(f'DROP DATABASE "{name}" WITH (FORCE)'))
        admin.dispose()


@pytest.fixture(autouse=True)
def clean_database(request: pytest.FixtureRequest) -> Iterator[None]:
    if (
        "db_engine" not in request.fixturenames
        and "just_contract" not in request.keywords
    ):
        yield
        return
    engine: Engine = request.getfixturevalue("db_engine")
    try:
        with engine.begin() as connection:
            connection.execute(
                text("TRUNCATE payments, firm_payments_audit, firms RESTART IDENTITY")
            )
        yield
    finally:
        with engine.begin() as connection:
            connection.execute(
                text("TRUNCATE payments, firm_payments_audit, firms RESTART IDENTITY")
            )


@pytest.fixture
def db_connection(db_engine: Engine) -> Iterator[Connection]:
    with db_engine.connect() as connection:
        yield connection


@pytest.fixture
def client_factory(
    db_engine: Engine, monkeypatch: pytest.MonkeyPatch
) -> Iterator[ClientFactory]:
    monkeypatch.setenv(
        "DATABASE_URL", db_engine.url.render_as_string(hide_password=False)
    )
    monkeypatch.setenv("AUTH_ENABLED", "false")
    monkeypatch.setattr(session, "engine", db_engine)
    monkeypatch.setattr(main, "engine", db_engine)
    monkeypatch.setattr(health, "engine", db_engine)
    with ExitStack() as stack:

        def create() -> TestClient:
            return stack.enter_context(
                TestClient(main.app, raise_server_exceptions=False)
            )

        yield create


@pytest.fixture
def client(client_factory: ClientFactory) -> TestClient:
    return client_factory()


@pytest.fixture
def firm_factory(db_engine: Engine) -> SeedFirm:
    next_id = 0

    def seed(**overrides: Any) -> Firm:
        nonlocal next_id
        next_id = max(next_id + 1, overrides.get("id", 0))
        firm = FirmFactory.build(**{"id": next_id, **overrides})
        with db_engine.begin() as connection:
            connection.execute(
                text(
                    "INSERT INTO firms (id, name, balance_cents, uuid) "
                    "VALUES (:id, :name, :balance_cents, :uuid)"
                ),
                asdict(firm),
            )
        return firm

    return seed


@pytest.fixture
def transfer_case(firm_factory: SeedFirm) -> tuple[list[Firm], Payload]:
    firms = [firm_factory() for _ in range(4)]
    payer, recipient, other_recipient, _ = firms
    return firms, request_for(
        payer,
        PaymentFactory.build(payee_firm_uuid=recipient.uuid, amount="12.34"),
        PaymentFactory.build(payee_firm_uuid=other_recipient.uuid, amount="2.00"),
    )


@pytest.fixture
def pdf_example(firm_factory: SeedFirm) -> tuple[list[Firm], Payload]:
    firms = [
        firm_factory(
            id=1,
            name="Pinecrest CPA Group",
            balance_cents=5_000_000,
            uuid="3f1c9a2e-7b4d-4c1e-9a55-2d8e6f0b7c41",
        ),
        firm_factory(
            id=2,
            name="Lopez Bookkeeping",
            balance_cents=50_000,
            uuid="8b2e4c71-0d3a-4f6e-b1c9-5a7d2e9f4c10",
        ),
        firm_factory(
            id=3,
            name="Nair Tax Services",
            balance_cents=200_000,
            uuid="e5f18b3c-2a9d-4c07-8e6b-1d4a7f9c3b25",
        ),
    ]
    return firms, request_for(
        firms[0],
        PaymentFactory.build(
            payee_firm_uuid=firms[2].uuid,
            amount="6250",
            description="Overflow returns, August 2026",
        ),
        PaymentFactory.build(
            payee_firm_uuid=firms[2].uuid,
            amount="5800.5",
            description="Amended returns, August 2026",
        ),
        PaymentFactory.build(
            payee_firm_uuid=firms[1].uuid,
            amount="1200.75",
            description="Bookkeeping cleanup, 3 clients",
        ),
    )


@pytest.fixture
def database_snapshot(db_engine: Engine) -> Snapshot:
    def snapshot() -> dict[str, list[tuple[Any, ...]]]:
        with db_engine.connect() as connection:
            return {
                table: [
                    tuple(row)
                    for row in connection.execute(
                        text(f"SELECT * FROM {table} ORDER BY id")
                    )
                ]
                for table in ("firms", "payments", "firm_payments_audit")
            }

    return snapshot


@pytest.fixture
def database_failure(db_engine: Engine) -> Iterator[Failure]:
    installed: list[str] = []

    def install(table: str) -> None:
        assert table in {"payments", "firm_payments_audit"}
        condition = (
            "NEW.description = 'reject-this-payment'" if table == "payments" else "TRUE"
        )
        with db_engine.begin() as connection:
            connection.execute(
                text(f"""
                CREATE FUNCTION reject_test_insert() RETURNS trigger
                LANGUAGE plpgsql AS $$
                BEGIN
                    IF {condition} THEN
                        RAISE EXCEPTION 'private database failure';
                    END IF;
                    RETURN NEW;
                END $$;
                CREATE TRIGGER reject_test_insert BEFORE INSERT ON {table}
                FOR EACH ROW EXECUTE FUNCTION reject_test_insert()
            """)
            )
        installed.append(table)

    try:
        yield install
    finally:
        with db_engine.begin() as connection:
            for table in installed:
                connection.execute(text(f"DROP TRIGGER reject_test_insert ON {table}"))
            connection.execute(text("DROP FUNCTION IF EXISTS reject_test_insert()"))


@pytest.fixture
def existing_records(
    db_engine: Engine, transfer_case: tuple[list[Firm], Payload]
) -> None:
    firms, _ = transfer_case
    with db_engine.begin() as connection:
        connection.execute(
            text(
                "INSERT INTO payments (payer_firm_id, payee_firm_id, amount_cents, "
                "description) VALUES (:payer, :payee, 1, 'existing')"
            ),
            {"payer": firms[0].id, "payee": firms[1].id},
        )
        connection.execute(
            text(
                "INSERT INTO firm_payments_audit (request_id, raw_request) "
                "VALUES (:request_id, CAST(:body AS JSON))"
            ),
            {"request_id": str(uuid4()), "body": '{"existing": true}'},
        )
